# Generated by Django 5.2.9 on 2025-12-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('water', models.CharField(choices=[('muy_poca', 'Muy poca'), ('poca', 'Poca'), ('moderada', 'Moderada'), ('mucha', 'Mucha')], max_length=20)),
                ('light', models.CharField(choices=[('sombra', 'Sombra'), ('indirecta', 'Luz indirecta'), ('parcial', 'Luz parcial'), ('directa', 'Sol directo')], max_length=20)),
                ('fertilizer', models.CharField(choices=[('poco', 'Poco'), ('moderado', 'Moderado'), ('frecuente', 'Frecuente')], max_length=20)),
                ('location', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior'), ('ambas', 'Ambas')], max_length=20)),
                ('maintenance', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
