# Generated by Django 5.2.9 on 2025-12-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='plant_images/'),
        ),
    ]
